### ISSUE TITLE
JointGraphResources.get(...) is undefined

### ISSUE THREAD

**Issue by webaddicts** [elsix/angular-jointjs-graph#1]
Hey,
I basically used example you provided for this library and copied it into my project. The error 'JointGraphResources.get(...) is undefined' at 857:35 (angular-jointjs-graph.js) appears when I try to add a new node by drag and drop.
I have no back-end connection yet but i see there is no request send so I assume that is not a problem here.

**Comment by npetkov** [comment]
Please be so kind to provide the full trace.

However, I believe your assumption is wrong - the exception you see is most likely caused by the fact that there is no object provided by the backend on which a request can be initiated. The JointGraphResources factory is a simple store for the Resource objects captured by the main Graph directive, and if there aren't any resources stored there, no requests can be made to the backend.

**Comment by webaddicts** [comment]
Alright, thanks for explanation! Indeed it was caused by lack of back-end connection.

**Comment by npetkov** [comment]
No problem, thank you for your feedback.
